### ISSUE TITLE
Image in ./public/images/content/filename.jpg isn't served

### ISSUE THREAD

**Issue by benschwarz** [kolber/stacey#1]
As soon as I remove it from here, it serves. 
Must be an overzealous regex somewhere?

**Comment by kolber** [comment]
This is a tricky one. Technically the problem that you're running into is that 'content' is a reserved word as far as the rewrite rules are concerned (so are 'app' and 'public').
There is a relatively simple fix for this:
RewriteCond %{REQUEST_URI} !(app|public|content)/(._)$
becomes
RewriteCond %{REQUEST_URI} !^/(app|public|content)/(._)$
The problem with this is that the addition of the ^/ will break the ability to run stacey from a subfolder. Not really sure what best solution to this is at this point in time.

**Comment by benschwarz** [comment]
You're right, this is down right tricky to handle. It might be worth leaving the 'issue' open and coming back to it when we have a look at the routing system.

**Comment by kolber** [comment]
This issue is resolved with v1.2.
