### ISSUE TITLE
Twig merge filter with non-unique slug/folder-name?

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#102]
Hi,

i am using a snippet that was created for a client project with @kolber to "get all the pages from all the subfolders" then merging them all and rendering them out by date.
A strange problem occurred when some of the folder names (slug) has the same name.
Like if i have different category folders, with similar named subfolders (projects), for example two subfolders that are both named "1.project-1".

The problem here is that the merge filter merges all the projects, and only renders out one of the projects with the same folder name (slug). And it seems to work as long as all subfolders have unique id's/slug.

My question:
Is there another way to achieve this and be able to use non-unique folder names?

My folder structure (with comments):

```
/content
    /projects
        /category-1 
            /1.project-1    (not rendering)
            /2.project-2    (not rendering)
            /3.unique-1     (this renders)
        /category-2
            /1.project-1    (not rendering)
            /2.project-2    (not rendering)
            /3.unique-2     (this renders)
        /category-3
            /1.project-1    (this renders)
            /2.project-2    (this renders)
            /3.unique-3     (this renders)
```

My example:

```
{% set all_projects = [] %}
{% for child in page.children %}
    {% set all_projects = all_projects|merge(child.children) %}
{% endfor %}

{% for subchild in slice(sortbydate(all_projects,'date')|reverse) %}
    <!-- project -->
    <div>
        <a href="{{subchild.url}}">
            <small>{{subchild.date}}</small>
            <h3>{{subchild.title}}</h3>
            {% include "partials/assets/subchild-thumb.html" %}
        </a>
    </div>
    <!-- end project -->
{% endfor %}
```

Now what happens is that this renders out everything as expected, but only one of the two subfolders (in different category folders) that has the same name.

Hope you can understand this, and that maybe there is some way of dealing with this with Twig.

Thanks in advance.

**Comment by mjau-mjau** [comment]
Since the TWIG merge filter overwrites identical values, this will happen ... To be honest, I am not sure exactly how values are stored in **all_projects**, but I assume it must store all pages as objects somehow since it can access properties of each item in the 2nd loop.

You could maybe change line 2 to refer to the **page.permalink**, which is unique root-relative path:

```
    {% set all_projects = all_projects|merge(child.children.permalink) %}
```

But then you would likely need to somehow parse the value in the 2nd loop. Sorry I dont know, but perhaps try the above?

**Comment by o-l-e** [comment]
sorry @suncat100 it didn't work.
Thanks anyway though.
