### ISSUE TITLE
.htaccess authentication causing redirect issues

### ISSUE THREAD

**Issue by domenicomazza** [kolber/stacey#105]
Hi,

I've found line 40 in .htaccess for allowing basic authentication is causing issues with redirects. In my case parked domains weren't redirecting appropriately until I commented line 40. I'm not a .htaccess expert so I can't determine if this is specific to my web host's setup, I can say these are standard redirects placed by cPanel if this helps in testing.

Domenico.

**Comment by kolber** [comment]
Thanks for the heads up @domenicomazza.
I have made a small tweak to the htaccess file (8af32c0fb0bc27) which may address the issue.

**Comment by domenicomazza** [comment]
All fixed. Thank you @kolber.
