### ISSUE TITLE
Search result thumb.url and other result variables

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#107]
Hi, i can't seem to get the thumb.url or other result variables like result.date to work in the search.html template. I don't know if this is a bug, or if it is just not possible.

To explain:

```
This works fine:
<a href="{{result.url}}">{{result.title}}</a>

This fails to find it's path:
<img src="{{resize_path(result.thumb.url, 100, 100, 0, 95)}}" />

This fails, and prints out the same date on all the results:
{{result.date|date('d M, Y')|title}}
```

Thanks in advance :)

**Comment by raphaelbastide** [comment]
Any idea on how I can fix that?
I am kind of stuck :candy:

**Comment by samkingco** [comment]
I'm having the same issue too.

I also don't get any results when this is put on a server, but I get results when it's local and on the same version of PHP.

I'm pretty confused.

**Comment by o-l-e** [comment]
Hey, did anyone ever find a solutions to this?
