### ISSUE TITLE
Using variable within content: of .yml file in 3.0.0

### ISSUE THREAD

**Issue by briefwriter** [kolber/stacey#108]
In former versions of Stacey, one could do the following for the .txt file:

```
title: The SWF Project 6
-
date: 2009, Jun–
-
content: 
Lorem @date ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
```

and the variable @date shows up in the content as the date defined, as well as in any templates, etc.

For the Stacy 3.0.0 I've gotten variables to work pretty much everywhere, except for within the content area of the .yml file that is defining them in the first place. 

I'm sure I just do not know how to properly use. Using  {{ page.date }} within the content: does not work as is, but I'm assuming its a markdown issue? that needs some other sort of characters on the outside to allow ?

Sorry, I am not a professional coder, if it is my just not understanding the proper way to do this.

**Comment by pbatts** [comment]
Hello,
Though I only worked with the previous version for a very brief time before switching to 3.0.0, I can't imagine how that would have worked.

The variable can only be called from a template. Variables in <code>.yml</code> files won't work.

Hope that helps,

PB

**Comment by briefwriter** [comment]
It worked because the older version was a text file, not .yml I guess..., so variable could be called within it for the "Content:" part.... Oh well. Just means I'll have to put one more layer of templating in I guess...

**Comment by mjau-mjau** [comment]
YML files are supposed to strictly contain your content and variables, nothing else. Like @pbatts I can't see how or why that would have worked before. Even if it did, its poor logic because you are trying to do template-stuff in your content file, instead of in your template.

I can see why you would want to save some time with your example, but your content files are not supposed to work like that.

**Comment by briefwriter** [comment]
I totally understand deblobbing chunks, and keeping data separate from templates, etc. I am a database developer (FileMaker Pro, Server, Advanced, ), and can tell you horror story after horror story of trying to deal with people's data who did not.  My reasoning was not because I wanted to save time, or not develop good templates, it was for a very specific reason within one of the websites I had. It is not longer an option, so I'll deal.  

I just wanted to make sure that I was not missing something, as I have not dealt with YAML a lot, and my professional "coding" experience is limited to HTML, CSS, Twig, and advanced scripting within FileMaker.  Thus, I would not consider myself a real coder.  I always assume an issue is from my own lack of knowledge first, so needed to make sure I was not missing something rather basic. 

Thanks for all your help, I just needed to verify. 

I've been enjoying working with Stacy, and it overall flexibility.

I'll go ahead and close the issue.

**Comment by pbatts** [comment]
@briefwriter I'm not sure it would help, but, you can still use txt files instead of yml files.

PB
