### ISSUE TITLE
Nasty BUG: Pages go blank in Safari browsers (osx + ios)

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#109]
I am experiencing a strange and rather nasty bug on Stacey sites.

Now i originally thought this was an Apple/OSX/iOS/Safari bug, but after trying various browsers (Chrome, Firefox and Opera, all latest versions) and other sites, i am afraid that this could actually be a Stacey + Safari issue.

What happens is that sometimes pages go completely blank, and when viewing the source shows that the page has not loaded at all.

I managed to reproduce this error by installing a clean version of Stacey (3), and going through the following steps using Safari both on OSX (Lion and Mavericks) and iOS 6 or 7 (tested on iphone 4 and 5):
1. enter the front page
2. click on "Projects"
3. click to the front page again
4. refresh the page using "Command + R"
5. Page goes completely blank, no matter how much you refresh

Now my tests on my iphone are even more sensitive, and break even when you refresh on step 2 (Projects).

This has also happened when browsing a Stacey website "normally", and is a real nightmare when i am testing a site having to refresh all the time.

One could argue that users don't repeatedly refresh sites, but this happens often in iOS, and is a real problem.

Anyone else having this bug?
Any idea what could be the reason?

Excuse me if this turns out to be a non-Stacey issue, but i simply can't figure it out.

**Comment by Snip1** [comment]
I've not been able to replicate either on my local install or on your link above.  Sorry :(

**Comment by o-l-e** [comment]
thanks @Snip1, i would blame my internet connection, location or something, but my colleague has the same problem located in a completely different country.

**Comment by kolber** [comment]
Wow, that's an interesting find @o-l-e. It looks like this is the issue (see the article's first comment as well).
http://tech.vg.no/2013/10/02/ios7-bug-shows-white-page-when-getting-304-not-modified-from-server/
That is definitely non-standard behaviour by Safari.

**Comment by o-l-e** [comment]
Thanks for the quick reply @kolber, and it's good to hear that i am not going crazy :)

I tried to search for Safari-related issues first, but i did not search for the right terms (304).
I also now recall that this problem started after upgrading to iOS7 and latest OSX Safari.

So would the fix the article suggests be an htaccess thing, or is it more complicated?
I wish i could help with this one, but my server side skills are minimal.

**Comment by o-l-e** [comment]
Thanks @kolber, seems to do the job :)
Lets hope Apple fixes this soon.

**Comment by juanjoseluisgarcia** [comment]
How does Apple explain that Safari 7 doesn't pass the acid 2 test anymore? It draws orange striped in the eyes of the image...

**Comment by JohnsCurry** [comment]
I've managed to find a problem just like this. Not sure what "Stacey" is, but I get this on Safari browser only when I go to the page with the problem, navigate to another page, navigate back, then press refresh. Once I do this procedure I need to restart my server to remedy. Mine is a Rails 4 app

**Comment by o-l-e** [comment]
@JohnsCurry have you updated Stacey to the latest version?
It did the job here.

**Comment by JohnsCurry** [comment]
Sorry I may be a bit noobie, but what exactly is stacey? Is it a Gem?

**Comment by fillmember** [comment]
@JohnsCurry Stacey is a flat-file, PHP CMS. Check it out at https://github.com/kolber/stacey/
