### ISSUE TITLE
Twig Horizontal Reuse

### ISSUE THREAD

**Issue by pbatts** [kolber/stacey#110]
I'm not sure if this is a bug or I'm not doing something correctly. I can't get Twig's horizontal reuse to work. I am expecting the words "content here" to appear on the web page. Anyone using Twig's "use" tag?
http://twig.sensiolabs.org/doc/tags/use.html

This is what I have.
Template, test.html

<pre><code>
{% extends "default.html" %}
{% use "blocks.html" %}

{% block test %}{% endblock %}
<code></pre>

Template, blocks.html

<pre><code>
{% block test %} content here{% endblock %}
<code></pre>

Thanks,

PB

**Comment by mjau-mjau** [comment]
I am guessing this is because the feature is not available in the TWIG version integrated with Stacey. I upgraded TWIG in Stacey to latest version, because I needed some of the newer filters. You can upgrade TWIG, but there are some issue to get it to work, read this thread #72 ...

**Comment by pbatts** [comment]
Thanks @suncat100, that was my first thought also but I found the parser here:
app > parsers > Twig > TokenParser > Use.php

The php stuff is over my head so I'm stuck.

Regarding this issue, I'll add that, nothing breaks. But nothing renders.

Thanks,
PB

**Comment by kolber** [comment]
Hey @pbatts, I'm not sure you need to be using `use` here.
`use` is actually a pretty complicated templating concept. What it actually does is inherit the `{% block %}`s from another template, but not the content of the blocks themselves.

I'm pretty sure you should be able to get what you're looking to achieve by taking a different approach.

**Comment by pbatts** [comment]
Thanks, @kolber. I'll look for an alternative.

PB
