### ISSUE TITLE
Twig random function

### ISSUE THREAD

**Issue by raphaelbastide** [kolber/stacey#111]
I am trying to use the [random](http://twig.sensiolabs.org/doc/functions/random.html) fuction I found on the Twig’s doc. Stacey return `The function "random" does not exist`. Does Stacey include just a part of Twig? Or maybe it is a version problem?

**Comment by mjau-mjau** [comment]
You need to upgrade TWIG in your Stacey setup. Unfortunately, there are some complications, and you will need to edit a few files manually. The process is covered here if you want to give it a shot: #91 , and a related issue here #77 . Hopefully a new version of Stacey will have TWIG updated at some point.

**Comment by raphaelbastide** [comment]
Thank you for your answer. I’ll bypass the issue because my project is too advanced enough to update TWIG.
