### ISSUE TITLE
How to get localized date information in stacey 3 ?

### ISSUE THREAD

**Issue by tasinttttttt** [kolber/stacey#116]
Hey!
I found the 'Intl' Twig extension is specifically made for that ((http://twig.sensiolabs.org/doc/extensions/intl.html) but then I couldn't figure out how to activate the extension on stacey. Any thoughts?

**Comment by mjau-mjau** [comment]
_// me commenting on old Stacey issues_

That would likely be added in the file `template-parser.inc.php` below the line where it says `$twig->addExtension(new Stacey_Twig_Extension());`. You would likely add it like this on a new line: `$twig->addExtension(new Twig_Extensions_Extension_Intl());`.

I am not 100% sure that extension is included in the TWIG version that comes with Stacey.
