### ISSUE TITLE
Rendering the frontpage?

### ISSUE THREAD

**Issue by kariemil** [kolber/stacey#117]
What is the standard way to render the frontpage and its content in Stacey? Is it to use the /content/index/ folder? How come there's no index.html file in /templates/ to match index.yml by default? Is /content/index/ used in any other context?

**Comment by o-l-e** [comment]
@kariemil there used to be an index.html template, but a "non-exitsting template" falls back to the default.html template. If you look at the default.html, it is the same as the index.html used to look like. If you create your own index.html template, it will override the current fallback default.html.

The deafult.html template is a fallback for any template name that does not exist. So if you name your page whatever.yml it will fall back to the default.html. The default is useful during development stages when templates have not been defined, and of course if you name the .yml wrongly.

**Comment by kariemil** [comment]
Thank you. But what is the proper way to render the actual homepage, the root index.html so to speak, of the website? Where do I place assets for it? Content?

**Comment by o-l-e** [comment]
/index
  index.txt
  1.image.jpg
  thumb.jpg
  etc
