### ISSUE TITLE
Extensions directory

### ISSUE THREAD

**Issue by kariemil** [kolber/stacey#121]
I find the /extensions directory a bit bothersome. As far as I am concerned, as a minimally technical user of Stacey, it is a do-not-touch zone. I like the idea that the /app directory being the only such area. Would it be possible to move /extensions into /app?

**Comment by mjau-mjau** [comment]
_// me just looking through some threads and commenting_

I guess the idea would be that /app is Stacey, and should remain untouched, whereas /extensions could technically be extended- or changed by yourself without affecting Stacey core ...

**Comment by kariemil** [comment]
Then why is SLIR in /app?

**Comment by mjau-mjau** [comment]
_shrugs_ I don't really see any reason why everything couldn't be inside the /app folder as you suggest, although one could argue that SLIR is an essential part of the Stacey app ... Just the way it is I guess ... ;)

**Comment by o-l-e** [comment]
i think @kolber's idea was that this was a place where people could create their own extensions/plugins.
So in other words not really a "do-not-touch-zone" like the app-folder.

Ps: close the issue if you agree ;)
