### ISSUE TITLE
Stacey 3 and localhost?

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#125]
I am trying to set up Stacey 3 with localhost, and have almost gotten it right, but i am getting an error when using resized images. Any idea how this could be solved?

Attaching a screenshot of the placeholder image added by SLIR.

Thanks

![index-php](https://cloud.githubusercontent.com/assets/881495/4056129/247250d2-2db5-11e4-9bec-c10554769da5.png)

PS: Let me know if there is any other info i can give in order to identify the problem.

**Comment by o-l-e** [comment]
PS: Using latest OSX 10.9.4

**Comment by kariemil** [comment]
I wonder if this is related to my issue regarding clean urls while running from ~/Sites rather than /Library/WebServer/Documents.

**Comment by o-l-e** [comment]
This issue was related to the php version i was using.

A fix for the related [issue here](https://github.com/kolber/stacey/issues/161).
