### ISSUE TITLE
possible to display assets in name order rather than grouped by filetype?

### ISSUE THREAD

**Issue by ghost** [kolber/stacey#126]
Is there any way to make this worK?

eg. if i have 01.jpg, 02.mov, 03.jpg, 04.html in a project folder can they display in that order rather than lumping the images together?

many thanks.

**Comment by o-l-e** [comment]
i ran into a similar thing, and got this working thanks to @mjau-mjau.

Try this:

```
{% for asset in page.files %}
    {{asset.file_name}} <br />
{% endfor %}
```

you could also try to exclude the text-file if you need to (change .txt to .yml if needed)

```
{% for asset in page.files if ".txt" not in asset.url %}
    {{asset.file_name}} <br />
{% endfor %}
```

Good luck!

**Comment by o-l-e** [comment]
@luckystairs did this work for you?
If so, close the issue ;)

**Comment by ghost** [comment]
Yes – thanks. Put me on the right track. Crash course in twig and a bit of reworking the template files.
