### ISSUE TITLE
Cache php issue

### ISSUE THREAD

**Issue by kariemil** [kolber/stacey#128]
After updating a page, the index is now displaying:

```
Warning: Invalid argument supplied for foreach() in /var/www/virtual/kaffivagninn.is/htdocs/app/cache.inc.php on line 36
```

at the top. 

Line 36 of cache.inc.php says:

``` php
foreach($old_caches as $file) unlink($file);
```

I don't see the problem.

**Comment by kariemil** [comment]
It went away on its own, so it's probably not a huge issue but it might still be worth checking into?

**Comment by Sija** [comment]
`$old_caches` was not an array, thus the warning.

**Comment by mjau-mjau** [comment]
If someone has this problem again and wants it fixed indefinitely, substitute the following code on line 36 of **cache.inc.php**:
`foreach($old_caches as $file) unlink($file);`
to:
`foreach((array)$old_caches as $file) unlink($file);`
