### ISSUE TITLE
Running stacey from localhost/~username

### ISSUE THREAD

**Issue by kariemil** [kolber/stacey#129]
Working in `/Library/WebServer/Documents` can be a pain because every change requires authentication, so I wanted to move the file to `~/Sites`. I followed instructions found online about how to set this up. However, clean URLs do not work in this environment. I've tried `chmod` and `chown _www`. I also tried to figure out if it had anything to do with httpd.conf but it doesn't seem to (it already says `AllowOverride All`). Any idea what the issue is?

**Comment by pbatts** [comment]
Hello,
Are you still having trouble running from ~/Sites? If yes, the first step is to config your machine to show hidden files. It will require command line execution in terminal if you are comfortable with that.
I've been running from ~/Sites for quite some time and can't imagine doing it any other way.
Regards,
PB

**Comment by mjau-mjau** [comment]
Should be pretty straight-forward, you just need to change Apache to point to ~/Sites folder, and it should not really affect Stacey ...

**Comment by kariemil** [comment]
I figured this out. It was an issue with Yosemite, where some of the setup process has been changed. I was eventually able to figure it out, though.

**Comment by pbatts** [comment]
@kariemil Thanks for letting us know that you got it fixed.
