### ISSUE TITLE
JSON.minify

### ISSUE THREAD

**Issue by svnlto** [kolber/stacey#13]
The currently returned JSON isn't clean enough to actually work with. for example, jQuery ajax method won't even deal with it. on the other hand, having  conditional statements in the JSON template adds whitespace which generally bad when dealing with JSON.

would you consider adding this: 

https://github.com/getify/JSON.minify

s

**Comment by kolber** [comment]
Yes, this is a good point. Not to mention that the JSON currently shipping with the app fails validation.

I will look into this. It might also be nice to strip out any trailing commas left in the JSON file automatically.

**Comment by kolber** [comment]
These issues have been addressed with https://github.com/kolber/stacey/compare/a0cba70c...463ac2f1

**Comment by svnlto** [comment]
I get 'function json_minify undefined' where did you add minify.json to your project so it's getting picked up?

**Comment by kolber** [comment]
Ugh. I should know better than making commits on a Sunday night.
See: f01b8647b627bd82eeebf4f45f065539b0801914

**Comment by svnlto** [comment]
Thanks for that! it perfectly validates now too.

**Comment by kolber** [comment]
And you don't need to worry about trailing commas any more, they will be automatically stripped out before being served.
