### ISSUE TITLE
Stacey for "normal people"

### ISSUE THREAD

**Issue by kariemil** [kolber/stacey#130]
I made a little website in Stacey for a restaurant. It works great and I've learnt a lot about the app which I'm now using to redo all my personal sites. However, I've run into a snag with updates. The client wants to be able to update prices on the menu herself – I was managing all content up until now. 

So I started researching and I have looked into everything: Dropbox integration (the host won't allow me to install Dropbox), setting up a cronjob to sync a local folder corresponding to /content on her computer (still haven't been able to but might still work), using some applet like FTP dropper (doesn't allow the updating of entire folders, only individual files, and it costs money, and it's not reviewed that well), setting up an Automator script to update a local copy of /content (see here http://editkid.com/upload_to_ftp/, not sure it will work – I've never used automator before and it doesn't seem to have the exact functionality I'd like it to have) and finally using OS X's Watched Folder functionality (which has the issue of not updating recently edited files, only recently added files, so it won't work). 

Currently, no option seems tenable, and using the plain old FTP client seems like the only solution, but I'm pretty sure my client will freak out if I tell her that's how she has to do it. The yml files will scare her enough. I'm a bit worried that I've made a mistake by using Stacey for this website and that I'll have to either redo it or... I don't even know. Does anyone have suggestions? Anyone done something like this?

**Comment by kariemil** [comment]
For the record, I have settled on two ways of doing this for the time being:
1. Mounting the /content folder using Panic's Transmit (if people are willing to pay) or
2. Using Cyberduck and giving the client ftp access only to /content, using the local editing feature so they don't have to deal with downloads and uploads (if people are not willing to pay).

Both options require me to have a backup and to set up a cron job for keeping that backup up-to-date somewhere in case the client deletes everything or overwrites everything or otherwise causes mayhem.

My dream pet project is to create a simple web interface for access to the /content folder for Stacey. Has anyone done work on such a project?

**Comment by pbatts** [comment]
@kariemil thanks for the update. An interesting and challenging situation. I had a similar need in the past and ended up using a different CMS. I would be very interested in a safe and simple method for accomplishing this and being able to use Stacey.

PB

**Comment by mjau-mjau** [comment]
@kariemil May I ask exactly how you were storing "prices on the menu"? I assume somehow in the YML files, but I don't quite understand the structure. Perhaps you have a link to the website? I have been working on a basic admin panel that works with Stacey, see more here:
https://github.com/kolber/stacey/issues/113#issuecomment-62345683

**Comment by kariemil** [comment]
The prices were simply stored in a YML file. I ended up going with Cyberduck for now, which can edit directly to the server. I hope I'll be able to upgrade my client to your admin panel at some point :) It looks great.
