### ISSUE TITLE
theme folder

### ISSUE THREAD

**Issue by svnlto** [kolber/stacey#15]
have you considered having a themes folder containing multiple themes, instead of only a templates folder i.e. 

/themes/stacey-default-theme
/themes/my-custom-theme
/themes/another-custom-theme

simply because, currently if I'd like to develop a different theme for a site I need to first make a copy of the site and then replace the templates folder..

does this make sense?

i could imagine setting the current theme in the _shared.txt or something..

**Comment by kolber** [comment]
If the name of the "/templates" folder was easily customisable, this would allow you to develop multiple themes as described above wouldn't it?

**Comment by svnlto** [comment]
that wouldn't make much sense I guess. there should be either a /templates or /themes folder which can take multiple subfolders (themes/templates).

how would you find out which folder in the root is the /template folder if you can just randomly name them?

**Comment by kolber** [comment]
If there was a high-level variable that was simple to modify, couldn't you just point at "/themes/theme-1", "/themes/theme2", etc. rather than "/templates"?

**Comment by svnlto** [comment]
yeap, I think another one like "theme" or "template" in _shared.txt maybe?

**Comment by svnlto** [comment]
is this something that could be easily integrated ?

**Comment by kolber** [comment]
Yea, I don't think it would be too complicated.
