### ISSUE TITLE
iteration with children

### ISSUE THREAD

**Issue by svnlto** [kolber/stacey#17]
if I run the following i get the error below.

{
  "data": [
    foreach $parent do
      foreach $children do
        foreach $children do
        {"name": "@page_name"},
        endforeach
     endforeach
    endforeach
  ]
}

will result in breaking the json output with the following error:
http://pastie.textmate.org/private/lkpnnvbyqmxvfi71kf6lkq
(it's a bit verbose)..

the json this will output validates fine tho

let me know if you need more details on this.

**Comment by kolber** [comment]
The problem is that the code you're using is causing a recursive loop. The problematic area is the `foreach $children ...` nested within `foreach $parent ...`.

You will need to look at refactoring, perhaps using `$siblings` instead, or listing out the entire tree from the top down.

**Comment by svnlto** [comment]
fixed. I ended up using partials for this since the folder structure is quite deep.
