### ISSUE TITLE
testing out 3.0 ...

### ISSUE THREAD

**Issue by bumpux** [kolber/stacey#29]
... after using 2.3 pretty regularly. Running locally on mac / apache. Home page loads fine, but trying to browse to any project sends this error: 

Not Found

The requested URL /Users/G/Sites/sandshed/stacey3/index.php was not found on this server.

Wherever i click it's looking for (and failing to find) index.php .

**Comment by kolber** [comment]
How are you running Stacey? Through MAMP, or through the pre-installed PHP?
And what does your `.htaccess` file look like?

**Comment by bumpux** [comment]
Pre-installed Apache/PHP on Snow Leopard. "sandshed/" is an aliased directory defined in httpd.conf. I've run various instances of Stacey 2.3 under /sandshed/\* with no trouble.  

Other than updating RewriteBase the .htaccess should be the same as default. Here it is : 

RewriteEngine on

# Some hosts require a rewritebase rule, if so, uncomment the RewriteBase line below. If you are running from a subdirectory, your rewritebase should match the name of the path to where stacey is stored.

# ie. if in a folder named 'stacey', RewriteBase /stacey

#RewriteBase /sandshed/stacey3/

ErrorDocument 404 /404.html

# Rewrite any calls to *.html, *.json, *.xml, *.atom, *.rss, *.rdf or *.txt if a folder matching \* exists

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !public/
RewriteCond %{DOCUMENT_ROOT}/public/$1.$2 !-f
RewriteRule (.+).(html|json|xml|atom|rss|rdf|txt)$ $1/ [L]

# Add a trailing slash to directories

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !(.)
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteRule ([^/]+)$ $1/ [L]

# Rewrite any calls to /\* or /app to the index.php file

RewriteCond %{REQUEST_URI} /app/$
RewriteRule ^app/ index.php [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ index.php?$1 [L]

# Rewrite any file calls to the public directory

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !public/
RewriteRule ^(.+)$ public/$1 [L]

**Comment by kolber** [comment]
So it still doesn't work if you set the RewriteBase explicitly?

Do sub-pages work if you rename the `.htaccess` file?

**Comment by bumpux** [comment]
Right, I've been setting RewriteBase explicitly all along in any case.
What should I rename .htaccess to?

On Jan 16, 2012, at 10:32 PM, Anthony Kolber
reply@reply.github.com
wrote:

**Comment by kolber** [comment]
I can't actually think of any reason why 3.0 rewriting would work any differently to 2.3 rewriting, nothing has changed! 

You can rename the `.htaccess` to anything (`_htaccess` perhaps?) and Stacey will drop back to using non-rewrite-based URLs (eg. `/?/contact`).

If the `/?/` URLs work correctly once you've renamed the `.htaccess` file then that means the problem is somewhere between the `.htaccess` file and the `httpd.conf` file. So, that will at least narrow things down.

Also, with the htaccess file named `.htaccess`, if you uncomment the `RewriteBase /sandshed/stacey3/`, do you get your original "failed to write cache" error?

**Comment by kolber** [comment]
Apologies for the 20 questions, local file issues are the hardest to debug...

**Comment by bumpux** [comment]
Ah. I'm working too late :- ). Fixed this by rolling back some
fiddling I'd done to httpd.conf. It's all working now with clean urls
and all. Sorry for the false alarm!

Looking forward to checking out the new templating syntax. At first
glance it seems more verbose, but possible worth it due to twig
capabilities? I'll keep exploring when better slept ...

Greg

On Jan 16, 2012, at 10:44 PM, Anthony Kolber
reply@reply.github.com
wrote:

**Comment by kolber** [comment]
Ah, all good, I know how it is.

Yea, it is a little more verbose, but it is hugely powerful. Have a play around with it when you get a chance and let me know what you think.
