### ISSUE TITLE
A reference to a partial within a template does not work if the reference is the first "data" in the template

### ISSUE THREAD

**Issue by thor** [kolber/stacey#3]
The issue at hand is that a template with a reference to a partial as the first thing will render the partial not being included.
# Example files
## partial.html

```
<a href="/">link me!</a>
```
## template.html

```
:partial
    <p>Random gibberish.</p>
```
# Result
## Expected result

```
<a href="/">link me!</a>
    <p>Random gibberish!</p>
```
## Actual result

```
:partial
    <p>Random gibberish!</p>
```

**Comment by kolber** [comment]
Thanks for pointing this out.

I've pushed up a fix and in the process made the partial matching a little more robust.
http://github.com/kolber/stacey/commit/257a6628a724c74f9b982f2a0353184441b15e0b
