### ISSUE TITLE
Quite difficult to install

### ISSUE THREAD

**Issue by rnmp** [kolber/stacey#35]
I haven't been able to install Stacey on most servers out there. I was only using it locally.

http://d.pr/V128

I set the permissions as the installation says.

**Comment by kolber** [comment]
Things have changed a little with version 3.0.
You will need to allow write permissions for PHP for each of the folders inside "/app/_cache" as well as the "/app/_cache" folder itself.

**Comment by rnmp** [comment]
That's what I did, also. Now I get this error:

```

Warning: mkdir() [function.mkdir]: SAFE MODE Restriction in effect. The script whose uid/gid is 195528/195528 is not allowed to access app/_cache/templates/45/6a owned by uid/gid 25000/25000 in /f5/bandd/public/app/parsers/Twig/Environment.php on line 950

Warning: tempnam() [function.tempnam]: SAFE MODE Restriction in effect. The script whose uid/gid is 195528/195528 is not allowed to access app/_cache/templates/45/6a owned by uid/gid 25000/25000 in /f5/bandd/public/app/parsers/Twig/Environment.php on line 953
Failed to write cache file "app/_cache/templates/45/6a/69052615a663e52659628e6583a8.php".
```

**Comment by kolber** [comment]
It looks like your host has some fairly serious file restrictions in place.
Your best bet will be to get in touch with them and ask the best way to allow PHP write access to a series of folders.

**Comment by rnmp** [comment]
Actually. I'm still figuring out which server to use. Which one will you recommend me. I'm only using PHP servers because of Stacey. (I know this is totally off-topic)

**Comment by kolber** [comment]
I hear MediaTemple are pretty good. I haven't tried them myself though.

**Comment by kolber** [comment]
I also just pushed up a fix, so if your template cache folder is unwritable, then it will disable template caching.
This may be a short-term answer to your problems.

https://github.com/kolber/stacey/commit/be769773b6ea170da350dba1e2c2ceefcbaf7b3e

**Comment by rnmp** [comment]
Great! This pretty much solved everything. I was about to suggest that flexibility. Thank you!
