### ISSUE TITLE
Absolute vs relative path variable

### ISSUE THREAD

**Issue by f0x2501** [kolber/stacey#39]
In Stacey 3 / twig you have the {{ path }} variable you can use for linking in the current folder.
But it's a relative one.  (../../pathtomyimage)

Do you plan to introduce a variable with absolute path for linking (like with base_url, permalink ...) ? It'll be useful for rss content for images to appear in rss aggregator.

Do you plan a variable usage in editing feature like in stacey 2:  define variables or use page variables inside content section ?

Thanks !

**Comment by kolber** [comment]
Don't relative paths work correctly in rss aggregators?

**Comment by f0x2501** [comment]
Yes in some planet, I need to hardcode:

```
![](domain/{{ path }}/tomyimage)
```

othewise picture doesn't appear on planet.

But in my rss reader is ok ...

Maybe there is an uurl domain tag in rss feed description  ? (I've made a rss template because atom don't fit with the planet)  

Thx.

**Comment by Sija** [comment]
@kolber: relative paths are real PITA, another example where they miserably fail is when you pass them to the flash player in which case you can't tell is it relative to the page OR to .swf lying somewhere in `public` folder. I'd strongly advise against 'em.

**Comment by kvakes** [comment]
I've created a Twig filter for files in `/content`. I used it to get HTML5 video to work. You could use it like this: `{{ video.url|absolute }}`. Will it be useful?

**Comment by kolber** [comment]
That sounds very helpful. Would you like to open a pull request?

**Comment by kolber** [comment]
I have merged in @kvakes absolute path Twig filter.
It's working really nicely.
