### ISSUE TITLE
A little friendly PR advice...? 

### ISSUE THREAD

**Issue by iDGS** [kolber/stacey#40]
A) I'm on _your_ side.

B) A good concept--e.g., Stacey--should stand or fall on it's own merits.

C) IMHO the video that plays in the download demo, "Game Boy Game Girl..." distracts and detracts from the otherwise good concept and execution of Stacy itself. 

1) Does it provide any additional clarification, insight, help or other support having to do with your "product" (Stacey)? (Nope.)

2) Does it build your brand? (Nope.)

3) Does it support or promote other work(s) related to advancing your immediate/other interests? (Maybe; it depends on your point of view.) 

4) Does it amuse your friends and show you to be a way-cool dude? (yeah, sure--but there's a time and place for everything, and IMHO this just ain't it).

So, that "Friendly PR (Public Relations) advice" -- Pick something else.  Something more useful and applicable to your goals with this project.  I think it will better help your cause.

Yet, I know people are certainly allowed to have views other than mine--I'm okay with that.  It's just a little sad when they intermingle something so far off-topic and of questionable taste that it works against them.  E.g., the whole "Mother Effin'..." labeling of otherwise _great_ "products" (I use the term "products" loosely) by my revered heroes Paul Irish and friends. Gratuitous bluster like that takes attention away from what's really important.  Think: The genuinely big dogs don't have to bark.  It's the chihuahuas that make the most noise.  Unfortunately I couldn't convince Paul of that either.

Peace & Love, bro.

Respectfully yours,
/a friend

**Comment by iDGS** [comment]
P.S. BTW, I would be remiss if I failed to congratulate you on the very best installation instructions I have seen anywhere, _ever_, for a product like this!  (Especially loved the expert use of yellow highlighting :)

Thank you!

**Comment by kolber** [comment]
Thanks for taking the time to post this detailed commentary @iDGS. I think you're right, what was acceptable for much lesser-known project, is perhaps not as a passable now.

Also, thanks for the kind words.
