### ISSUE TITLE
Prune old branches perhaps?

### ISSUE THREAD

**Issue by kvakes** [kolber/stacey#55]
Hi Anthony,

I've noticed that there are three other branches that are pretty much not used anymore. When people clone your repo they also clone those branches. I think they all are merged to master now, so it's a good idea to delete them not only from your local repo, but from github too.

``` bash
git branch -d yaml
git push origin :yaml
```

The first line deletes your local branch, the second deletes 'yaml' branch from github.

**Comment by kolber** [comment]
Thanks for the reminder.
