### ISSUE TITLE
Twig & variables avaible in yml file

### ISSUE THREAD

**Issue by f0x2501** [kolber/stacey#58]
Let me ask if we can hope more - Stacey or shared - variables will be available in yml files ?
Generally is it good or bad idea to let Twig templating language use in yml files and be parse like markdown ?
It will be very convenient for example to use resize_path with SLIR for images.

Thx !

**Comment by kolber** [comment]
Generally, it wouldn't be a great idea to expose all of the Stacey/shared variables to the text files, as this would slow things down quite a bit.

That said, I do want to add `resize_path`, as it would be extremely helpful within the text files.

**Comment by f0x2501** [comment]
Thanks for `resize_path` it will be great ! 

Sorry to reactivate an old request but I think absolute path is more valuable in content than relative. 

In Stacey 2.0 the shared / local variables were usable in text files, so I always put my domain name in a global var to use it in txt files. 

Now in 3.0  I code:

```
 ![](http://domain/{{ path }}/tomyimage)
```

do you plan to add a var like this ?

```
![]({{ absolute_path }}/tomyimage)
```

Big kudo.

**Comment by kolber** [comment]
Yea, agreed, I think I do need to add an absolute_path variable as well.

**Comment by f0x2501** [comment]
Great ! 
with resize_path and absolute_path you make my day.
