### ISSUE TITLE
Version 3 is staible ?

### ISSUE THREAD

**Issue by alimd** [kolber/stacey#63]
Stacey v2.3 released 1 years a go.
I see stacey updated to v3.
what is v3 release date ?
what exactly change logs ? or diff ro v2.3
and can i us it now ?
is it staible ?

**Comment by nchpmn** [comment]
+1.

Is 3.0 still a work-in-progress, Kolber?

Thanks :)

**Comment by kolber** [comment]
There are a few more things I want to get in there before officially released v3.0.
That said, the version currently on Github is being used on production sites and can be considered stable.
