### ISSUE TITLE
Error starting Stacey

### ISSUE THREAD

**Issue by poneteonline** [kolber/stacey#66]
Just started a new stacey test site with ver 3.0 - already running 2.3 with no problems.
But starting, I'm getting following error:

Warning: Invalid argument supplied for foreach() in /EmI2/app/cache.inc.php on line 36

Fatal error: Class 'Twig_Extension' not found in /EmI2/app/parsers/Twig/Extension/Core.php on line 16

**Comment by gregcoleinfo** [comment]
I think this might be more of a forum issue.

Anyway, we need information on what you did to reach this error. At the root of your site, do you have a folder titled "extensions", with 2 files inside it "config.php" and "twig-extensions.inc.php"?

**Comment by Mulchio** [comment]
I am having the same issue, but just the Warning, not the Fatal error (do have those files in the "extensions" folder).

The warning showed up immediately after installing Stacey 3.0 in a completely new folder on the server, following the Stacey instructions. Permissions on all folders and files look correct.

Here is line 36 of cache.inc.php: 
    foreach($old_caches as $file) unlink($file);

I will post it in the forum as well.

**Comment by Mulchio** [comment]
UPDATE:
my bad. problem solved.
make sure you set the correct permissions to all content of app/_cache

**Comment by tmewett** [comment]
I am still getting this error, regardless of the `chmod` settings on the `app/_cache` folder.

**Comment by tmewett** [comment]
Funnily enough, today this error message disappeared. Hooray! :)

**Comment by Mulchio** [comment]
great.!!
there must be something in the air today.
