### ISSUE TITLE
sometimes asset-collection fails to parse text variables

### ISSUE THREAD

**Issue by aegagros** [kolber/stacey#69]
I have had problems with the same bug in the past, and used other workarounds (see [here](https://getsatisfaction.com/stacey/topics/stacey_3_0_gives_undefined_index_error#reply_10174668)). However, I found out that the asset data defined in the content text file (e.g. image description) failed to load, sometimes depending on the folder level (same file worked under 'content/' but not under 'content/some-other-folder'). Therefore, I thought of replacing the following lines 14-16 of asset-factory.inc.php:

``` php
    # return any page data scoped against the asset filename
    $page_data = self::$store[$page_path];
    return isset($page_data[$file_name]) ? $page_data[$file_name] : false;
```

with the following:

``` php
    # return any page data scoped against the asset filename
    $page_data = self::get($page_path);
    return isset($page_data[$file_name]) ? $page_data[$file_name] : false;
```

see my fork: http://github.com/aegagros/stacey

**Comment by kolber** [comment]
Thanks Manolis, I have merged this fix into the main codebase.
