### ISSUE TITLE
Some Lower Level Directories Not Displaying Properly

### ISSUE THREAD

**Issue by pbatts** [kolber/stacey#70]
Some of my lower level directories return the main index page when called rather than the proper content. Instead of the proper content being displayed when a link is clicked the main index content is displayed. This does not happen with all directories but only some directories. The problem appears to have started when my hosting provider upgraded the server PHP version to 5.3.2
I now have three identical Stacey V 3.0 sites running on three servers. My local server with PHP 5.3.15, Remote server1 with PHP 5.3.13 and remote server2 with PHP 5.3.2
Remote server2 is the only one that is not working properly.

Any ideas much appreciated.

Thanks,
Paul

**Comment by kolber** [comment]
Could you let me know if this is still a problem? I have just made a series of updates which I hope will address this.

**Comment by pbatts** [comment]
I've updated my local site with the latest .zip file and it breaks my site. Almost all, but not all, links return a 404.

Thanks

**Comment by kolber** [comment]
Okay, good to know. It must be a direct problem with `5.3.2` then.
I will have a look into it.

**Comment by pbatts** [comment]
Maybe not. I only got as far as testing it on my local installation which is running 5.3.15. When that didn't work, I did not test it on either of my remote servers.

**Comment by pbatts** [comment]
Just tested new files on remote server with PHP 5.3.13. Got same result, most but not all pages are broken and return a 404.

**Comment by tmewett** [comment]
I have the same issue, along with the "invalid argument" one, except the warning error message only appears on some of the pages -- even thought everything else is identical. I am running PHP 5.2

**Comment by kolber** [comment]
@tmewett the templating language we are using requires PHP 5.3+ and it causes some definite weirdness on 5.2.

@pbatts do you have any thoughts as to what could be causing your issues? I am running on 5.3.15 and there is nothing like the problems you have mentioned at all. I did some initial testing on 5.3.2 and couldn't find anything either. Have you made any particular customisations or have any strange installation quirks?

**Comment by tmewett** [comment]
Really? Correct me if I'm wrong, but I thought you were using Twig, which runs fine on 5.2. Or does your extension make use of some newer PHP features?

EDIT: Also I think it should be noted that **any** URL visited, regardless of if it's a page or not, displays the index (for me, anyway)

**Comment by pbatts** [comment]
@kolber There is one anomaly that seems related. I was, in one case, able to get the broken page to render by shortening the file name to (as I remember) 24 characters or less. Some of my file names may be 30 characters or more. Shortening the file name of the one did not, however, fix the children pages. I've opened a new, file name related, issue <a href="https://github.com/kolber/stacey/issues/86" class="issue-link" title="Use of Underscores in folder names">#86</a>. It may or may not be related.
Please note that the site is running on a PCI server.
Here is the <code>PHP</code> config.
![Screen Shot 2013-04-22 at 3 45 32 PM](https://f.cloud.github.com/assets/2254955/411265/439154ee-ab85-11e2-8d78-0f077a40762c.png)

**Comment by pbatts** [comment]
With issue #86 fixed (thanks again, kolber) I have confirmed that this issue with the lower level directories still exists. I will confirm the anomaly with the file names, mentioned earlier. I will also do some more poking around to see what I can find. The <code>PHP</code> version on the server is now up to 5.3.23.

pbatts

**Comment by kolber** [comment]
Thanks @pbatts let me know if you find anything. I have a suspicion that it may be something to do with using a windows server. It's tricky to tell as I don't have one to test with.

**Comment by kolber** [comment]
@tmewett it looks like the new version of Twig works on PHP 5.2, but the older version we are using requires PHP 5.3.

**Comment by pbatts** [comment]
@kolber I've spent a good bit of time looking at this and while I don't have anything concrete, I do have a little more info. The trigger is definitely loooong file names, though I can not see a pattern of what the threshold is for the number of characters that can be used before things break.
Here are a few examples.
This link will display properly. <code>mysite.com/products/onetwothreefourfivesixseven/</code>
This link breaks and displays the content of the main index page instead. <code>mysite.com/products/onetwothreefourfivesixseven/twothreefourfivesixseveneight/</code>
But if you shorten the name of the lowest level directory to <code>mysite.com/products/onetwothreefourfivesixseven/twothreefourfivesix/</code> it displays perfectly.
The files in the following directory structure display perfectly. <code>mysite.com/products/one/two/three/four/five/six/seven/</code>

I'm a little confused about your reference to a Windows server. I saw the word "Windows" in my PHP config but didn't know what it meant. Here is my server info.
![Screen Shot 2013-04-29 at 11 56 46 AM](https://f.cloud.github.com/assets/2254955/439541/99d8b468-b0e5-11e2-9a24-e98ed8d626e3.png)

Thanks

pbatts

**Comment by kolber** [comment]
Sorry, my mistake. I got confused by the `"c:\php\includes"` line.
I can verify that PHP5.3 on my ubuntu server is handling very long foldernames without any issues.

I wonder if something in your server configuration could be causing the conflict? Perhaps the server itself has issues with longer foldernames?

**Comment by tmewett** [comment]
@kolber ah, ok. However I think it should be noted that all the Twig on my index page works absolutely fine.
Also what @pbatts said regarding file name length does not seem to be the case with me. My _dodgy_ page was just called "hosting."

**Comment by pbatts** [comment]
At this point I must agree, the issue seems to be server related. My web host is changing out my server within the next couple of weeks. I am curious to see if anything changes.

@kolber We can close this issue as not being directly related to Stacey and I will add comment after the server change.
@tmewett Thanks for the input.

pbatts

**Comment by pbatts** [comment]
Final update. As promised, my host has finally moved my site to a new server. The new machine is running <code>php 5.8.8</code>. 

The problem still exists.

PB

**Comment by kolber** [comment]
Thanks for the update @pbatts, really glad to hear it is all working now. 
That was definitely a strange one.

**Comment by pbatts** [comment]
Unfortunately, I was a little premature in my excitement. It seems the problem persists. I'm convinced it is a config issue with the host. It runs perfectly on a second remote server I have.

Thanks again for all the help.

PB
