### ISSUE TITLE
Cool tip: A simple "cms" for editing Stacey content with mobile devices

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#76]
Hi, i just came across this cool little php script called OneFileCMS, and thought that maybe someone would see a use for it in combination with Stacey (or even better develop some sort of plugin or extension for Stacey 3).

https://github.com/Self-Evident/OneFileCMS
http://onefilecms.com/

Basically it lets you browse and create folders, files, upload images(even on iOS) or delete them through your browser. It also has a simple text editor field, so that if you want to create and write Markdown directly into txt files created on for example a touch device.

I have often thought that it would be nice to be able to edit Stacey content on a mobile device, and this little plugin lets you do just that. You could use it as a blog etc, as it lets you upload images from your mobile photos/camera roll.

To install:
I have done a test where i have placed the onefilecms.php in the root folder together with the stacey folder. After that simply access the "backend" by entering: 

```
        www.yourdomain.com/onefilecms.php
```

Then enter "username" and "password" and thats it.
You can of course change the user/password in the admin page.

The styling in the script is not that ideal for me, but i am tinkering around with it to make it more friendly for my mobile. 

Hope this can be useful for others, and if someone has any other similar ideas/suggestions that are better please share.

**Comment by andremalenfant** [comment]
Thanks for sharing. I was just looking for a WYSIWYG editor for Stacey...

**Comment by o-l-e** [comment]
Good, you saw the plugin right?
https://github.com/Self-Evident/OneFileCMS/blob/master/plugins/tinymce_init.php

Please share if you do something with this :)

**Comment by andremalenfant** [comment]
Yes, just tried it...

First problem, onefilecms is very ugly ;) Not a big deal for now but...

Second, it would be even nicer to have a proper edit page where the user would edit the content field in TinyMCE (and the other field in separate edits). Not only this would be nicer, but it would allow for tighter security.

But until then, that is a viable alternative with almost no effort.

Thanks again!

**Comment by o-l-e** [comment]
Hey,

i have been discussing the design in the issues, and the developer admits to the visual part you are referring to :)
But, he is open to suggestions, and i was thinking a nice minimal and responsive design would be really nice, just like Stacey. 
https://github.com/Self-Evident/OneFileCMS/issues/24

I don't know any php, but i can handle css ok. I was thinking of giving it a try when i have time.
