### ISSUE TITLE
$previous_sibling exists for first page in collection

### ISSUE THREAD

**Issue by jshawl** [kolber/stacey#79]
Let's say I have two pages in my collection:

work/
   /project-2/ => 2.project-2
   /project-1/ => 1.project-1

If I'm on /project-2/, $previous_sibling will return project-1, even though it's the first page in the collection. 

Is there anyway to list the $previous_sibling only if it's not the first page (@is_first) in the collection?

**Comment by kolber** [comment]
This should be fixed now Jesse.
