### ISSUE TITLE
Markdown parser fails to convert '---' into '&mdash;'

### ISSUE THREAD

**Issue by russellbits** [kolber/stacey#80]
In brief, '---' (three hyphens) does not convert to '&mdash;' in the content in a content.yml file.

I would assume that this was a problem with the markdown parser with the exception that I am using the same exact parser (copied code) on another project (Wordpress) and do not get the same result. Perhaps this is a conflict because of the '---' delimiter in YAML? Can an exception to it be made for markdown content?

**Comment by kolber** [comment]
I believe in the version of Markdown we are using (http://michelf.ca/projects/php-markdown/extra/), three hyphens are used to delineate a h2. If you want to use an em dash, you could use either the character itself `—` or `&mdash;`. Either would work.

**Comment by russellbits** [comment]
I like the three hyphen convention, but you're right, the actual `—` works just find. Thanks.
