### ISSUE TITLE
URLs; clean sub-directory URLs work, top directory URLs don't

### ISSUE THREAD

**Issue by russellbits** [kolber/stacey#81]
Anyone have any idea why my top level URLs are requiring the `?/` in between the domain and page, while my subdirectory articles work just fine without it? For instance, `domain/articles` does not work while `domain/?/articles` does work, and yet `domain/aritcles/articletitle` works just fine? I can't yet see anything in `.htaccess` that could be causing this.

**Comment by kolber** [comment]
Have you tried clearing your page cache? It sounds like it could be caused by some older pages being cached with unclean urls and some not.

**Comment by russellbits** [comment]
If clearing your cache is accomplished by just deleting the files in the _cache directory, then yes I tried that to no effect.

To be more clear about what is happening, `domain/articles` results in the _index page_ being called (but without proper links to stylesheets and the like). `domain/?/articles' results in the`category.html`template being called properly and`domain/articles/articletitle` works fine.

I'm starting to notice a pattern here. The old Stacey had an index.html template, but I'm noticing that this version does not.

**Comment by russellbits** [comment]
The code squeezed me, it hammered me to the point of desperation. And in that desperation, I turned to a man that I didn't fully understand: rm*

The results were not pretty, but Stacey seems to be working just fine now. I guess I'll never know what the problem was.
