### ISSUE TITLE
Wrap content & prevent newline

### ISSUE THREAD

**Issue by itskingori** [kolber/stacey#82]
Is it possible to wrap content at lets say ... 80 characters and avoid the \n (newline) character inserted by YAML.

This would avoid having looooooong lines.

Any ideas/pointers?

**Comment by kolber** [comment]
I think the best, most simple solution would be to turn on text-wrapping in your text editor.
It would be very difficult to handle this in Stacey itself.

**Comment by itskingori** [comment]
I have.

I use Sublime Text 2 and have the text wrapped at 80 characters.

However ... at each _actual new_ line \n is added as opposed to a new line added at the end of the paragraph/block

Have a look at [this ... three_trailing_newlines_in_literals](http://www.yaml.org/YAML_for_ruby.html#three_trailing_newlines_in_literals)

I also tried [this ...](http://www.yaml.org/YAML_for_ruby.html#three_trailing_newlines_in_literals)

Examples are from the Ruby cookbook that you mention somewhere.

I don't think the issue is Stacey though as you can see from the link, after YAML is done ... the result has the \n after every actual line.

The result of course is that people will have to write long lines like [this ...](https://github.com/itsmrwave/kingori.co/blob/master/content/minutae/1.2013/1.04/1.httpurlconnection-getresponsecode-error/minutia.yml)

Unless there's something obvious I'm missing.

Oh, and the 80 character thing was just an example ... didn't actually intend for Stacey to do it.

**Comment by kolber** [comment]
Ah, I see what you're saying.
[This change](https://github.com/kolber/stacey/pull/43) introduces Github-style line breaks, thus introducing your problem. :P

I find less technical users tend to find the default Markdown linebreak handling confusing. Which was the reason for the change in the first place.

**Comment by itskingori** [comment]
@kolber So, I forked Stacey and implemented this itsmrwave/stacey@cc176d2d43e3ddf312535e9d50af2993f5d1d69e

In summary ... I;
- edited the `extensions/config.php` and included a preference (boolean - to use gfm-style or not to use)
- edited markdown parser to check what condition was set from `Config::$md_gfm_style_linebreaks`
- `require_once` the config file in the markdown parser file

Now, this is the part I'm not too comfortable with ... I thought I didn't have to `require_once` the config file since its included in the Stacey index.php file but I think without this `Config::$md_gfm_style_linebreaks` is not in scope and has no value etc etc

However, looking at the `app/parsers/template-parser.inc.php` you are able to access `Config::$templates_folder` ... being the creator and all, you would be able to determine if this was the right approach or I was just being lazy :-)  ... if the latter, maybe you could point me in the right direction?

And thanks for the [tip](https://github.com/kolber/stacey/pull/43), saved me a lot of time.

_Ps: If this 'hack' is inline with your vision going forward I could submit a pull request later_

**Comment by itskingori** [comment]
This was my fix, submitted as pull #85 if its ok.
