### ISSUE TITLE
Fenced Markdown within captions?

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#83]
Hi, and great to see the activity, and great work!

I was wondering if it would be possible to have fenced markdown within the descriptions, or other assets? 

Kind of like this:

```
    01.jpg:
      description: +++
         This is a Markdown caption.
         This is a new line with a < link >
         +++
      credit: +++
         This could be another block.
         A < link > etc.
         +++
```

Or would this complicate things?

Anyway, the descriptions inside the documents with the other content is a very nice addition.

Keep it up :)

**Comment by russellbits** [comment]
I don't know about fencing the information in the way that you have, but I have an index page with multiple variables that get called and they all contain markdown. For each of them I use a pipe, though (as opposed to fencing).

So your example could look like this:

``````
image: 01.jpg
image_desc: |
  This is an image caption *with* markdown
image_credit: |
  [credit to name](url-with-name)```
``````

**Comment by o-l-e** [comment]
This may be a stupid question, but how do i achieve multiple lines with line breaks or other markup?

```
 01.jpg:
  description: 
    # This is a h1.
     This is a Markdown caption paragraph.
    - This is a list
    - This is a list
    - This is a list
  credit: 
     # This could be another block.
     A < link > etc.
```

What would be nice with this ability, is to for example have a project slide slideshow (or similar), with a detailed decription of each slide. This is something that i think could be useful for a lot of portfolios out there.

But again, if this is a hard to achieve there are probably ways around it.
I really like the possibility of have all the text content, variables and image/video/embed descriptions in one single document.

**Comment by kolber** [comment]
If you use @ruzels suggestion and just throw a pipe character after the colon, then multiple lines should work as well. Or are they not?

**Comment by o-l-e** [comment]
i am sorry but @ruzels suggestion doesn't work, and i don't know how to show/reproduce you guys the error :(

**Comment by russellbits** [comment]
One common error is that you have to be sure that there is a new line followed by two spaces after the pipe character. (Because of the YAML specification, tabs will not work in this situation.) Is your web site printing an error? You can copy and paste it here for us to look at.

**Comment by o-l-e** [comment]
Hi again, i have tried the double space like you suggested, but still nothing.
The output html is blank.

Here is what i have, and just so there is no misunderstandings i will use \* to describe the spaces used:

```
01.jpg:
**description:*|  
****# Markdown caption here with an h1 for example? 
**photo:*|  
****# Photo caption here with an h2 for example? 
```

To explain further, my image name is 01.jpg, and i have two variables at a sublevel of this image.
The sublevels are "description" and "photo", and i have wrapped these with a div each in the markup.
Now this example above still only has one line of text under each variable, so i still don't know how to do multiple lines of markdown in each "sub variable".

Sorry to make this difficult, but this is the only way i can describe it.
Ps: I am using a Stacey version downloaded on the 6. of April 2013, 10 days ago.

**Comment by kolber** [comment]
Ah, yes, you're right!
The associated page data wasn't getting parsed as Markdown.
I have pushed up a fix for this now.

Just one thing to keep in mind, the `# Heading` format will be treated as a comment by the yaml parser, so you're better off using the

```
Heading
----------
```

and

```
Heading
==========
```

formats.

**Comment by o-l-e** [comment]
thanks for that, i will give it a try!
