### ISSUE TITLE
Use of Underscores in folder names

### ISSUE THREAD

**Issue by pbatts** [kolber/stacey#86]
This morning I downloaded (zip) and updated my local Stacey site. My site was immediately broken. I've tracked the issue to my use of underscores in folder names. Any page that is called will return a 404 if the folder containing the <code>.yml</code> file contains an underscore in the folder name.

I believe this issue started with updates to StaceyApp on or around April 9.

Thanks,
pbatts

**Comment by kolber** [comment]
Ah, nice pickup @pbatts. It looks like a typo introduced that bug.
Should be fixed with [2988cd](https://github.com/kolber/stacey/commit/2988cd2413f2c2c43719d25d8593ec401e01102c).

**Comment by pbatts** [comment]
Cool, thanks for the fix @kolber.
