### ISSUE TITLE
non-Stacey directories still end up with "stuff" in the URL

### ISSUE THREAD

**Issue by russellbits** [kolber/stacey#87]
I have a couple of directories that projects separate from Stacey (in my top-level directory). Given the way that the .htaccess file is written now, I can access them just fine. However, if I access them _without_ a trailing slash, things get funky.

This: `domain.com/someRealDir`

becomes

`domain.com/someRealDir/?controller=somefolder&action=&query=`

I see in .htaccess where a trailing slash should be added but 

`RewriteCond %{REQUEST_FILENAME} !-d`

would seem to indicate that it is not adding them to non-Stacey directories.  I wish I understood more about Apache's rewrite rules anyway, so I'll plug away at this, but is anyone else able to replicate this problem?

**Comment by kolber** [comment]
It sounds like there may be another .htaccess file somewhere causing your issue.
Stacey doesn't ever add any `controller` or `actions` stuff to the URL by itself.
