### ISSUE TITLE
Is it possible to sort by a specific field?

### ISSUE THREAD

**Issue by boedlen** [kolber/stacey#90]
Is it possible to sort by a specific field in Stacey?

Something like

```
{% for child in page.children | sort('author') %}
  <li>
    <a href="{{ child.url }}">{{ child.title }}</a>
  </li>
{% endfor %}
```

I cannot find any documentation about this function aside from a headline in the Wiki.

**Comment by kolber** [comment]
Hey Martin, as it happens there is a custom Twig method which can do this called `sortby`.
https://github.com/kolber/stacey/blob/master/extensions/twig-extensions.inc.php#L150

The usage is
`{% for child in sortby(page.children, 'author') %}`
