### ISSUE TITLE
Possible to set page = get(" {{ page.variable }} ") or other method to make a project preview?

### ISSUE THREAD

**Issue by o-l-e** [kolber/stacey#97]
I am trying to create a typical front page on a portfolio website, and would like to show specific highlighted projects as teasers or previews and place them on the index page.

Now this is what i am trying to achieve (though obviously not working):

In the index.yml i create a variable that contains the url to the project i want to highlight:

```
title: Index
teaser_1: /projects/project-1
teaser_2: /projects/project-2
```

Then i tried the following code in the index.html template:

```
{% block teaser %}
{# Place variable content url from "teaser_1: /projects/project-title-1" inside the set page #} 
{# like this: get("/projects/project-1 ") #}

{% set page = get(" {{ page.teaser_1 }} ") %}
<a href="{{page.url}}">
    <h2>{{page.title}}</h2>
    <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
    <p>View this project ></p>
</a>
{% endblock %}
```

Now this does not work for some reason, and i am really not very good at twig/yaml.

So does anyone have any other ideas on how to achieve this?
I think it it would be really useful in many cases.

Please help!

Ps: I don't want to create duplicates of a project, as i want the projects to stay in their original location.

**Comment by mjau-mjau** [comment]
Just access your custom variables like you would access the other page variables.

``````
{{ page.teaser_1 }}
{{ page.teaser_2 }}
<a href="{{ page.teaser_1 }}">link</a>```

Or are you trying to include parts of the URL specified in the variable? I don't think you can do that ... Actually I don't know in Stacey if you can access content from another page at all, regardless of saving the URL as variable.
``````

**Comment by o-l-e** [comment]
Hey, and thanks for the reply.

Yes i am trying to include parts of the URL specified in the variable.
The old Stacey was very flexible in this way, as you could basically inject a variable into anything in the html template. 

I don't know if this is even possible, but it would be really useful to "fetch" any specific project (with it's parts) and show it on the front page.

Any other ideas?

Thanks.

**Comment by mjau-mjau** [comment]
well, you can easily "inject" a variable with 3.0 also, but I don't think you can "get" content from another page by URL or PATH. I agree it would be useful.

However, its slightly more complicated ... What exactly would the function return? The markdown? The pages content? the html rendered with the given pages templates? Remember, when you normally work with a "page" or "child", basically you are referring to an object with variables {{page.item}}, and such should be the case when pointing to another page also ... alas I don't think its possible, although one day it would be cool to see some more extensive docs because right now we can only guess what gems are hidden away in Stacey.

**Comment by Sija** [comment]
and how about `{% set teaser_one = get(page.teaser_1) %}` ?

**Comment by mjau-mjau** [comment]
That will get the value of the variable, which would be "/projects/project-1" in this case ... but the idea here is to get the content of the page in the specific path.

**Comment by o-l-e** [comment]
That is correct @suncat100. The point is to highlight a chosen project by using the .txt/.yml document, without "disturbing" the project's location.

**Comment by mjau-mjau** [comment]
It would be useful with a method to access page content based on path/url.

There is perhaps a workaround, as long as project pages are childs or grandchilds of the current page, which I believe in your case is root/index?

```
{% for child in page.children %}                           
{% if child.title === "Projects" %}
{% for child in child.children %}   
     Get anything from a project page in here, child.title, child.description. child.content.
{% for image in child.images %}
     <img src='{{ resize_path( image.url, "730", "", "2:1", 95) }}'>
{% endfor %}
{% endfor %}
{% endif %}
{% endfor %}
```

**Comment by kolber** [comment]
@Sija is right, the only problem with the code you posted originally is this line:
`{% set page = get(" {{ page.teaser_1 }} ") %}` as Twig doesn't do inner string parsing within `{% %}` tags.
Just change that line to read:
`{% set page = get(page.teaser_1) %}`
and everything should work as you expect it to.

**Comment by o-l-e** [comment]
Yes, i worked!
Can't believe it was that simple :)

Thanks a lot guys.

**Comment by mjau-mjau** [comment]
what exact output do you get from that? To me it looks like your just setting a variable 'page'.

``` % set page = get(page.teaser_1) %
```

**Comment by o-l-e** [comment]
@suncat100 if it's me you are asking, it does what i set out to achieve.

Just to sum it up, for others that want to do the same:
First i insert one or more variables in my index.txt or .yml, with the URL to the project(or any page) i want to highlight.

```
title: Index

content:
++++++++++++++++++++++++++++++++++++++++++++++++
My content text here
++++++++++++++++++++++++++++++++++++++++++++++++

teaser_1: /projects/project-1/
teaser_2: /projects/project-5/
teaser_3: /projects/project-10/
```

Then, in my index.html template:

```
<!-- first the standard content -->
{{page.title}}
{{page.content}}

<!-- the "teaser" titles, thumbs and links to the projects -->
{% if page.teaser_1 %}
    {% block teaser_1 %}
        {% set page = get(page.teaser_1) %}
        <a href="{{page.url}}">
            <h2>{{page.title}}</h2>
            <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
            <p>View this project >> </p>
        </a>
    {% endblock %}
{% endif %}

{% if page.teaser_2 %}
    {% block teaser_2 %}
    {% set page = get(page.teaser_2) %}
        <a href="{{page.url}}">
            <h2>{{page.title}}</h2>
            <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
            <p>View this project >> </p>
        </a>
    {% endblock %}
{% endif %}

{% if page.teaser_3 %}
    {% block teaser_3 %}
        {% set page = get(page.teaser_3) %}
        <a href="{{page.url}}">
            <h2>{{page.title}}</h2>
            <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
            <p>View this project >> </p>
        </a>
    {% endblock %}
{% endif %}
```

This renders the following html:

```
Index
<p>My content text here</p>

<a href="./projects/project-1/">
    <h2>Project Title 1</h2>
    <img src="./render/w100-h100-c0-q95/1.projects/1.project-1/thumb.jpg" />
    <p>View this project >> </p>
</a>

<a href="./projects/project-5/">
    <h2>Project Title 5</h2>
    <img src="./render/w100-h100-c0-q95/1.projects/5.project-5/thumb.jpg" />
    <p>View this project >> </p>
</a>

<a href="./projects/project-10/">
    <h2>Project Title 10</h2>
    <img src="./render/w100-h100-c0-q95/1.projects/10.project-10/thumb.jpg" />
    <p>View this project >> </p>
</a>
```

This way i can control what projects i want to show on my front page, instead of just showing the latest ones by date or chronological order.

Now i don't know if there are any simpler ways of doing this (like not having to repeat teaser_1, _2 and _3 in the markup), but this will do what i want it to do. As my "non-coding" colleague will also handle publishing, it can't be a manual function.

If anyone has any ideas of simplifying or developing this idea further, i would be glad to hear them.

Ps: it would be nice to have some kind of snippet page or wiki for different ways of using Stacey with twig and Yaml. I am lousy at Twig, so your help is really helpful to me.

Thanks again!

**Comment by mjau-mjau** [comment]
nice1 ... I wouldn't have guessed that you could just get a page object by {{ page_slug_variable.property }} with Stacey, just replacing the methods available with the current page object.

**Comment by o-l-e** [comment]
i bet there are tons of things you could do with Stacey, and wish i knew more twig :)

**Comment by o-l-e** [comment]
Solution posted here:
https://github.com/kolber/Stacey-Snippets/wiki/Page-teasers

**Comment by pbatts** [comment]
@o-l-e Thanks for an incredibly awesome and powerful snippet. I am using a variation on this to eliminate duplicate and triplicate content data files (<code>.yml</code>) on my eCommerce site where some items fit into more than one category. I am also using it to enhance category pages by pulling in accessory and enhancement items from other categories.

And thanks to @Sija and @kolber for helping make this happen.

**Comment by o-l-e** [comment]
@pbatts great to hear!
If you have a variation of it, please share one the snippets page :)

**Comment by mjau-mjau** [comment]
Nothing wrong with your code of course, but just because I like optimizing stuff, here is an alternative! The code is more compact as it loops through teasers, and therefore also offers more flexibility in the amount of teasers one wants to use:

``` yaml
teasers: /projects/project-1/ /projects/project-5/ /projects/project-10/
```

``` twig
{% set teasers = page.teasers|split(' ') %}
{% for teaser in teasers %}
  {% set page = get(teaser) %}
  <a href="{{page.url}}">
    <h2>{{page.title}}</h2>
    <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
    <p>View this project >> </p>
  </a>
{% endfor %}
```

**Comment by o-l-e** [comment]
Hey that's a nice one @mjau-mjau, brilliant!
The nice thing about your version is that you can have as many teasers as you want.

Would it be possible to list the links vertically, with two spaces before, like this?

```
teasers: 
  /projects/project-1/
  /projects/project-5/ 
  /projects/project-10/
```

This way it would work like the image.description variable.

Ps: The "split" filter requires a later version of Twig than the current version of Stacey, for those who are trying to do this. There is a pull request or a fork somewhere that has this.
I was going to share snippet yesterday that uses split, but i got stuck trying to explain this.

**Comment by mjau-mjau** [comment]
I can see that is slightly more functional for the user ... problem is, then we can't use `split(' ')` safely to make an array from it. It could work, but the code when then need to search for line-break to make the array with `split('\\n')`. I am not quite sure if that works!

Do you have a reference link to the image.description variable?

**Comment by o-l-e** [comment]
Look at line 5-6:
https://github.com/kolber/stacey/blob/master/content/1.projects/1.project-1/project.yml

**Comment by mjau-mjau** [comment]
That is **object** notation though (see the key:value -> description:caption):

``` yaml
01.jpg:
  description: CAPTION
```

It could be used for teasers also, but it would have to look like this:

``` yaml
teasers: 
  teaser: /projects/project-1/
  teaser: /projects/project-5/ 
  teaser: /projects/project-10/
```

Perhaps not so beneficial any more? Still would allow more flexibility in the code to loop through items, but the user-input does not offer any major advantages.

**Comment by mjau-mjau** [comment]
Actually now I am wondering if you could do the following:

``` yaml
teasers: 
  - /projects/project-1/
  - /projects/project-5/ 
  - /projects/project-10/
```

**Comment by o-l-e** [comment]
hm, i don't know much about the hardcore stuff @mjau-mjau.
But, i still think it could be a nice option, and easier to read.

**Comment by o-l-e** [comment]
i kind of like you previous solution, because then i can change the variable names like this example:

```
teaser: 
  page: /projects/project-1/
  page: /projects/project-5/ 
  page: /projects/project-10/
```

Only an example, but it feels like the same logic, if you know what i mean :)

**Comment by o-l-e** [comment]
Come to think of it, the looping-part in your solution is definetly a huge advantage!

**Comment by pbatts** [comment]
@o-l-e <a href="https://github.com/kolber/Stacey-Snippets/wiki/Variation-on-Page-Teasers">Variation on Page Teasers</a> posted to <a href="https://github.com/kolber/Stacey-Snippets/wiki">Stacey Snippets</a>

I'm not so sure it is a variation rather than a different explanation/example of how it can work.

**Comment by pbatts** [comment]
Also created snippets <a href="https://github.com/kolber/Stacey-Snippets/wiki/Looping-with-Teasers">Looping with Teasers</a>

**Comment by mjau-mjau** [comment]
@o-l-e just to be a lid on this, I was slightly mistaken in my last reference. Basically you can use an **[array]** or an **[object]** to create the structure in your YAML, but if you are using an object, you wouldn't be able to use the same key name "page" for all items. These are your options basically for a loop-version:

Array Reference

``` yaml
teaser:
  - /projects/project-1/
  - /projects/project-5/ 
  - /projects/project-10/
```

Object Reference

``` yaml
teaser:
  page1: /projects/project-1/
  page2: /projects/project-5/ 
  page3: /projects/project-10/
```

As you can see in the reference above, you would need to create unique key names for the pages, and from a pure technical perspective, an object is unnecessary and the array version is more minimalistic. In both cases however, you can use the same loop code because TWIG will automatically distinguish between Array and Object:

``` twig
{% for item in page.teaser %}
  {% set page = get(item) %}
  <a href="{{page.url}}">
    <h2>{{page.title}}</h2>
    <img src="{{resize_path(page.thumb.url, 100, 100, 0, 95)}}" />
    <p>View this project >> </p>
  </a>
{% endfor %}
```

I was looking up the various methods of creating collections (arrays or objects) in YAML [here](http://yaml4r.sourceforge.net/doc/page/collections_in_yaml.htm).

**Comment by o-l-e** [comment]
@mjau-mjau i see. At least i think i see.

Your solution is absolutely a good one, in fact i have always wondered what cool things you can do with YAML in Stacey. It seems like there are many possibilties that have not been explored yet. Maybe we should tag the snippets with "twig" or "yaml" somehow?

In other words, arrays are more than welcome :)

**Comment by mjau-mjau** [comment]
YAML is quite cool ... You can build a data-structure at any depth in a syntax that is readable by both humans and machines alike, and easily access/loop through the data in twig/php.

**Comment by o-l-e** [comment]
@mjau-mjau and @pbatts i am going to have to try out your snippets later, but very inspiring guys!
